language: node_js
sudo: false
addons:
  code_climate:
    repo_token: '81249493bc927d59e073e8de89a9386e6178112dc3d0b5d71b91034194ab801c'
install:
  - "npm install npm -g"
  - "npm install"
script:
  - "gulp travis"
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
cache:
  directories:
    - 'node_modules'
